In [3]:
import numpy as np

In [4]:
#divides range into equal space
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [5]:
#gives log of equally divided range
np.logspace(1,10,6)

array([1.00000000e+01, 6.30957344e+02, 3.98107171e+04, 2.51188643e+06,
       1.58489319e+08, 1.00000000e+10])

In [10]:
arr1 = np.array([[2,3],[10,11]])
print(arr1)
arr1.ndim

[[ 2  3]
 [10 11]]


2

In [11]:
#dimension inc with inc in brackets
arr1 = np.array([[[[2,3],[10,11]]]])
print(arr1)
arr1.ndim

[[[[ 2  3]
   [10 11]]]]


4

In [17]:
arr2 = np.arange(12).reshape(2,2,3)
print(arr2)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [18]:
arr3 = np.arange(12).reshape(2,2,3).T
print(arr3)

[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [19]:
arr2.T

array([[[ 0,  6],
        [ 3,  9]],

       [[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]]])

In [21]:
arr4 = np.arange(10).reshape(2,5)
print(arr4)
print(arr4.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [49]:
arr5 = np.arange(9).reshape(3,3)
print(arr5)

#slicing of array in row
print("--> slicing row wise")
print("-->",arr5[:2])
print("-->",arr5[:3])

#slicing column wise
print("--> slicing column wise")
print("-->",arr5[:,1])
print("-->",arr5[:,0])

#slicing row & column
print("-->",arr5[1:3,2])
print("-->",arr5[1:3,1:3])

arr5[1:1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--> slicing row wise
--> [[0 1 2]
 [3 4 5]]
--> [[0 1 2]
 [3 4 5]
 [6 7 8]]
--> slicing column wise
--> [1 4 7]
--> [0 3 6]
--> [5 8]
--> [[4 5]
 [7 8]]


array([], shape=(0, 3), dtype=int32)

In [98]:
arr6 = np.arange(100).reshape(10,10)
print(arr6)
print("-->",arr6[6:7,4:6])
print("-->",arr6[5:8,0:2])
print("-->",arr6[5:6,0:2])
print("-->",arr6[7:9,8])
#print("-->",arr6[5:6,0:2][7:9])
#print("-->",arr6[])
s = slice(0,6,3)
#s1 =  slice()
print("-->",arr6[s])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
--> [[64 65]]
--> [[50 51]
 [60 61]
 [70 71]]
--> [[50 51]]
--> [78 88]
--> [[ 0  1  2  3  4  5  6  7  8  9]
 [30 31 32 33 34 35 36 37 38 39]]


In [72]:
s = slice(2,10,3)
arr6[s]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [73]:
arr6[2:10:3]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [100]:
print("-->",arr6[5,0:2])

--> [50 51]


In [103]:
#fromfunction
np.fromfunction(lambda x,y : x+y, (3,3), dtype = int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [108]:
#np.fromfunction?

In [106]:
#diagonal elements
arr6.diagonal()

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [107]:
# generates an array from function
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [152]:
def arr(x,y):
    return 10*x+y
np.fromfunction(arr, (3,3), dtype = int)

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [155]:
def arr(w,x,y,z):
    return 10*x+y
print(np.fromfunction(arr, (3,3,2,3), dtype = int))
np.fromfunction(arr, (3,3,2,3), dtype = int).ndim


[[[[ 0  0  0]
   [ 1  1  1]]

  [[10 10 10]
   [11 11 11]]

  [[20 20 20]
   [21 21 21]]]


 [[[ 0  0  0]
   [ 1  1  1]]

  [[10 10 10]
   [11 11 11]]

  [[20 20 20]
   [21 21 21]]]


 [[[ 0  0  0]
   [ 1  1  1]]

  [[10 10 10]
   [11 11 11]]

  [[20 20 20]
   [21 21 21]]]]


4

In [158]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
#axis1 = 1 means column , axis2 = 0 means row
# 1 : True , 0 : False
# axis1 : verticle axis , axis2 : horizontal axis
arr6.diagonal(offset = 3, axis1=1 , axis2=0)

array([30, 41, 52, 63, 74, 85, 96])

In [169]:
arr6.diagonal(offset = 3, axis1=True , axis2=False)

array([30, 41, 52, 63, 74, 85, 96])

In [123]:
#arr6.diagonal?

In [127]:
arr6.diagonal(offset = -3)

array([30, 41, 52, 63, 74, 85, 96])

In [200]:
#identity matrix
print(np.identity(5 , dtype='str'),"\n\n",np.identity(5 , dtype='float'),"\n\n",np.identity(5, dtype="int"))
print(np.eye(3))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']] 

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [195]:
arr7 = np.random.random(9).reshape(3,3)
arr7

array([[0.05704398, 0.38913871, 0.77711775],
       [0.09654649, 0.77323556, 0.18543211],
       [0.33342229, 0.35483592, 0.34749028]])

In [196]:
arr7.argmin(0)

array([0, 2, 1], dtype=int64)

In [197]:
arr7.argmax(0)

array([2, 1, 0], dtype=int64)

In [206]:
#sort the array
arr7.sort()
arr7

array([[0.05704398, 0.38913871, 0.77711775],
       [0.09654649, 0.18543211, 0.77323556],
       [0.33342229, 0.34749028, 0.35483592]])

In [209]:
arr7.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [214]:
# make a matrix of array
np.matrix(arr7)

matrix([[0.05704398, 0.38913871, 0.77711775],
        [0.09654649, 0.18543211, 0.77323556],
        [0.33342229, 0.34749028, 0.35483592]])

In [238]:
arr9 = np.random.rand(100).reshape(10,10)
print(arr9)

[[0.90441838 0.52200735 0.30623808 0.60887784 0.56002508 0.01733722
  0.09706655 0.41143422 0.85279716 0.76859995]
 [0.44977094 0.12553439 0.44963654 0.20807482 0.01575674 0.62972516
  0.71955034 0.67586212 0.88358123 0.03991839]
 [0.66931455 0.10443756 0.66835432 0.71280735 0.92568195 0.42061657
  0.97527451 0.52344187 0.15364617 0.59671637]
 [0.41154492 0.43338529 0.53500509 0.86505019 0.26218586 0.96012956
  0.28518378 0.17923859 0.32289131 0.58132217]
 [0.77235702 0.93426755 0.72141531 0.69203254 0.53728067 0.19945998
  0.20916799 0.94518625 0.44213137 0.21283952]
 [0.19623754 0.76611828 0.05782378 0.66541921 0.23914079 0.20877625
  0.29402039 0.83570289 0.14576729 0.45240862]
 [0.46346095 0.4431231  0.61725913 0.37100734 0.58795568 0.35656174
  0.03786123 0.45590957 0.14441062 0.36538201]
 [0.06421682 0.43646308 0.17395996 0.74110289 0.95051676 0.97207238
  0.03942103 0.95810177 0.71001212 0.33243054]
 [0.7791048  0.16758846 0.52312467 0.18360791 0.91201404 0.86543601
  0.9792693 

In [219]:
# takes exact position
print(arr9[7,7])

0.2608657091080575


In [220]:
# takes a range and shows in list
print(arr9[7:8,7])

[0.26086571]


In [272]:
l = [round(i[j],2) for i in arr9 for j in range(10)]
print(l)

[0.9, 0.52, 0.31, 0.61, 0.56, 0.02, 0.1, 0.41, 0.85, 0.77, 0.45, 0.13, 0.45, 0.21, 0.02, 0.63, 0.72, 0.68, 0.88, 0.04, 0.67, 0.1, 0.67, 0.71, 0.93, 0.42, 0.98, 0.52, 0.15, 0.6, 0.41, 0.43, 0.54, 0.87, 0.26, 0.96, 0.29, 0.18, 0.32, 0.58, 0.77, 0.93, 0.72, 0.69, 0.54, 0.2, 0.21, 0.95, 0.44, 0.21, 0.2, 0.77, 0.06, 0.67, 0.24, 0.21, 0.29, 0.84, 0.15, 0.45, 0.46, 0.44, 0.62, 0.37, 0.59, 0.36, 0.04, 0.46, 0.14, 0.37, 0.06, 0.44, 0.17, 0.74, 0.95, 0.97, 0.04, 0.96, 0.71, 0.33, 0.78, 0.17, 0.52, 0.18, 0.91, 0.87, 0.98, 0.91, 0.78, 0.45, 0.33, 0.88, 0.43, 0.46, 0.12, 0.81, 0.07, 0.56, 0.41, 0.12]


In [252]:
np.arange(l).reshape(10,10)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [258]:
# list to array
l1 = np.asarray(l)
print(l1)

[0.9  0.52 0.31 0.61 0.56 0.02 0.1  0.41 0.85 0.77 0.45 0.13 0.45 0.21
 0.02 0.63 0.72 0.68 0.88 0.04 0.67 0.1  0.67 0.71 0.93 0.42 0.98 0.52
 0.15 0.6  0.41 0.43 0.54 0.87 0.26 0.96 0.29 0.18 0.32 0.58 0.77 0.93
 0.72 0.69 0.54 0.2  0.21 0.95 0.44 0.21 0.2  0.77 0.06 0.67 0.24 0.21
 0.29 0.84 0.15 0.45 0.46 0.44 0.62 0.37 0.59 0.36 0.04 0.46 0.14 0.37
 0.06 0.44 0.17 0.74 0.95 0.97 0.04 0.96 0.71 0.33 0.78 0.17 0.52 0.18
 0.91 0.87 0.98 0.91 0.78 0.45 0.33 0.88 0.43 0.46 0.12 0.81 0.07 0.56
 0.41 0.12]


In [259]:
l1.ndim

1

In [260]:
l2 = l1

In [273]:
l3 = l2.reshape(10,10)
print(l3)

[[0.9  0.52 0.31 0.61 0.56 0.02 0.1  0.41 0.85 0.77]
 [0.45 0.13 0.45 0.21 0.02 0.63 0.72 0.68 0.88 0.04]
 [0.67 0.1  0.67 0.71 0.93 0.42 0.98 0.52 0.15 0.6 ]
 [0.41 0.43 0.54 0.87 0.26 0.96 0.29 0.18 0.32 0.58]
 [0.77 0.93 0.72 0.69 0.54 0.2  0.21 0.95 0.44 0.21]
 [0.2  0.77 0.06 0.67 0.24 0.21 0.29 0.84 0.15 0.45]
 [0.46 0.44 0.62 0.37 0.59 0.36 0.04 0.46 0.14 0.37]
 [0.06 0.44 0.17 0.74 0.95 0.97 0.04 0.96 0.71 0.33]
 [0.78 0.17 0.52 0.18 0.91 0.87 0.98 0.91 0.78 0.45]
 [0.33 0.88 0.43 0.46 0.12 0.81 0.07 0.56 0.41 0.12]]


In [274]:
l4 = l3

In [277]:
l5= l4.tolist()
print(l5)

[[0.9, 0.52, 0.31, 0.61, 0.56, 0.02, 0.1, 0.41, 0.85, 0.77], [0.45, 0.13, 0.45, 0.21, 0.02, 0.63, 0.72, 0.68, 0.88, 0.04], [0.67, 0.1, 0.67, 0.71, 0.93, 0.42, 0.98, 0.52, 0.15, 0.6], [0.41, 0.43, 0.54, 0.87, 0.26, 0.96, 0.29, 0.18, 0.32, 0.58], [0.77, 0.93, 0.72, 0.69, 0.54, 0.2, 0.21, 0.95, 0.44, 0.21], [0.2, 0.77, 0.06, 0.67, 0.24, 0.21, 0.29, 0.84, 0.15, 0.45], [0.46, 0.44, 0.62, 0.37, 0.59, 0.36, 0.04, 0.46, 0.14, 0.37], [0.06, 0.44, 0.17, 0.74, 0.95, 0.97, 0.04, 0.96, 0.71, 0.33], [0.78, 0.17, 0.52, 0.18, 0.91, 0.87, 0.98, 0.91, 0.78, 0.45], [0.33, 0.88, 0.43, 0.46, 0.12, 0.81, 0.07, 0.56, 0.41, 0.12]]


In [291]:
#seed fixes the random value
#float with seed
np.random.seed(0)
a = np.random.rand(9).reshape(3,3)
a

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [292]:
# exp with seed
np.random.seed(1)
a = np.random.rand(9).reshape(3,3)
a

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [290]:
np.random.seed(2)
a = np.random.rand(9).reshape(3,3)
a

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [296]:
# normal distribution
np.random.randn(100).reshape(10,10)

array([[ 0.48759421,  1.73907303,  0.0689698 ,  0.47324139, -0.65035502,
        -0.77910696, -0.77766271,  0.6225628 ,  0.42756207,  0.0740096 ],
       [-0.4531686 ,  0.60415364,  2.38520581, -0.12388333, -0.32419367,
         0.31075423,  2.46162831, -0.31612369, -1.81506277,  0.6842495 ],
       [ 0.03203253,  0.19627021,  0.90745116, -2.13483482,  0.81684718,
         1.18417131, -0.20448056, -0.11084446,  1.41448273, -1.416645  ],
       [ 0.67351346, -0.77229442, -0.09387704, -0.16977402, -0.54114463,
         0.53794761,  0.39128265,  2.21191487, -0.16224463,  0.29117816],
       [ 0.10806266, -0.19953292,  0.2328323 ,  0.15539326,  0.59372515,
        -1.35055772,  0.83056467,  0.11321804, -1.24274572,  1.59948307],
       [ 2.47441941, -0.33232485,  0.77714652,  0.09035118, -0.18659747,
         0.74325857, -0.41917807,  0.00496046, -0.83355727, -0.37935889],
       [-0.54362249,  1.08361763,  0.12180609,  0.65364026, -0.08915495,
         0.90087165,  1.40248666,  0.21768255

In [308]:
# int type random
a1 = np.random.randint(10, size=(3,3))
a1

array([[5, 1, 8],
       [0, 5, 3],
       [9, 0, 4]])

In [307]:
from numpy.linalg import inv

In [309]:
inv(a1)

array([[-0.08583691,  0.01716738,  0.15879828],
       [-0.11587983,  0.22317597,  0.06437768],
       [ 0.19313305, -0.03862661, -0.10729614]])

In [312]:
#Equation handling______________


In [317]:
# 3*x0 + x1 = 9
# x0 + 2*x1 = 8

a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(a,"\n",b)

[[3 1]
 [1 2]] 
 [9 8]


In [319]:
root = np.linalg.solve(a,b)
print(root)

[2. 3.]


In [323]:
type(root)

numpy.ndarray

In [324]:
root.ndim

1

In [328]:
c = inv(a)*b
c

array([[ 3.6, -1.6],
       [-1.8,  4.8]])

In [358]:
# where(cond/value , result, else result)
a = np.arange(10).reshape(5,2)
np.where(a<4,a,10*a)

array([[ 0,  1],
       [ 2,  3],
       [40, 50],
       [60, 70],
       [80, 90]])

In [331]:
np.where?

In [347]:
b = np.arange(9).reshape(3,1,3)
b

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

In [348]:
#gives elements from array
for i in b.flat:
    print(i)

0
1
2
3
4
5
6
7
8


In [349]:
# form 1-D array
b1 = b.ravel()
b1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [350]:
b1.ndim

1

In [357]:
# variance
b.var()

6.666666666666667

In [354]:
# standard deviation
b.std()

2.581988897471611