In [1]:
#numpy_____________

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
print(arr1*1, '\n', arr1/2, '\n', arr1+10, '\n', arr1-10)

[1 2 3 4 5] 
 [0.5 1.  1.5 2.  2.5] 
 [11 12 13 14 15] 
 [-9 -8 -7 -6 -5]


In [5]:
for i in "hello":
    print(i,end='')
    #print(i,end='\f')
    #print(i,end='\r')
    #print(i,end='\n')

hello

In [6]:
print(np.random.rand(6))
np.random.rand(6)


[0.19293219 0.44392715 0.74240509 0.71107187 0.50953703 0.80181813]


array([0.31343811, 0.60185979, 0.85325283, 0.54496814, 0.64883363,
       0.29957079])

In [7]:
print(np.random.randint(6))

0


In [8]:
arr1.size

5

In [1]:
import random
a = random.random()
print('%.3f'%a)

0.386


In [10]:
# Python code to demonstrate ceil(), trunc() 
# and floor() 

# importing "math" for precision function 
import math 

# initializing value 
a = 3.4536

# using trunc() to print integer after truncating 
print ("The integral value of number is : ",end="") 
print (math.trunc(a)) 

# using ceil() to print number after ceiling 
print ("The smallest integer greater than number is : ",end="") 
print (math.ceil(a)) 

# using floor() to print number after flooring 
print ("The greatest integer smaller than number is : ",end="") 
print (math.floor(a)) 


The integral value of number is : 3
The smallest integer greater than number is : 4
The greatest integer smaller than number is : 3


In [11]:
# Python code to demonstrate precision 
# and round() 

# initializing value 
a = 3.4556

# using "%" to print value till 2 decimal places 
print ("The value of number till 2 decimal place(using %) is : ",end="") 
print ('%.2f'%a) 

# using format() to print value till 2 decimal places 
print ("The value of number till 2 decimal place(using format()) is : ",end="") 
print ("{0:.2f}".format(a)) 

# using round() to print value till 2 decimal places 
print ("The value of number till 2 decimal place(using round()) is : ",end="") 
print (round(a,2)) 


The value of number till 2 decimal place(using %) is : 3.46
The value of number till 2 decimal place(using format()) is : 3.46
The value of number till 2 decimal place(using round()) is : 3.46


In [12]:
b = 7.15366
print('%.4f'%b)

7.1537


In [13]:
arr2 = np.array([[(1,2,3),(4,5,6)],[2,3,34,4]])
print(arr2)

[list([(1, 2, 3), (4, 5, 6)]) list([2, 3, 34, 4])]


In [14]:
#Multi-Dimension Array
arr3 = np.array([(1,2,3),(4,5,6),(7,8,9,0)])
print(arr3)
arr3

[(1, 2, 3) (4, 5, 6) (7, 8, 9, 0)]


array([(1, 2, 3), (4, 5, 6), (7, 8, 9, 0)], dtype=object)

In [15]:
arr4 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr4)
arr4

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr5 = np.array([(1,2,3,0),(4,5,6,0),(7,8,9,0)])
print(arr5)
arr5

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]


array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0]])

In [17]:
arr5.ndim   #2-D array(m x n)

2

In [18]:
arr3.ndim

1

In [19]:
arr6 = np.array([[(1,2,3),(4,5,6),(7,8,9,0)],[(11,12,13),(14,15,16),(17,18,19,20)]])
print(arr6)
arr6

[[(1, 2, 3) (4, 5, 6) (7, 8, 9, 0)]
 [(11, 12, 13) (14, 15, 16) (17, 18, 19, 20)]]


array([[(1, 2, 3), (4, 5, 6), (7, 8, 9, 0)],
       [(11, 12, 13), (14, 15, 16), (17, 18, 19, 20)]], dtype=object)

In [20]:
arr6.ndim

2

In [21]:
salary = (1,2,3,4,5,6)
a = np.array(salary)
print(a, a+a*0.2, a*0.9)


[1 2 3 4 5 6] [1.2 2.4 3.6 4.8 6.  7.2] [0.9 1.8 2.7 3.6 4.5 5.4]


In [22]:
arr7 = np.array([[2,3],[5,6],[8,9]])
print(arr7)

[[2 3]
 [5 6]
 [8 9]]


In [23]:
arr7.ndim

2

In [24]:
arr7.shape

(3, 2)

In [25]:
arr7.all

<function ndarray.all>

In [26]:
a=arr7.argmax
a

<function ndarray.argmax>

In [27]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
arr8 = np.arange(100).reshape(5,2,10)
print(arr8)

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [29]:
arr8.itemsize

4

In [30]:
np.ones((3,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [31]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [32]:
arr = []
while True:
    a = input("Want to enter list")
    if a == "y":
        ar = eval(input("Enter the elements"))
        arr.append(ar)
        
    
    else:
        break
arr9 = np.array(arr)
print(arr9)

Want to enter listy
Enter the elements[1,2]
Want to enter listy
Enter the elements[3,4]
Want to enter listy
Enter the elements[5,6]
Want to enter listn
[[1 2]
 [3 4]
 [5 6]]


In [33]:
a=eval(input("enter"))

enter[34,45,"3"]


In [34]:
a

[34, 45, '3']

In [5]:
import numpy as np
arr = []
while True:
    a = input("Want to enter list : ")
    if a == "y":
        ar = eval(input("Enter the elements : "))
        arr.append(ar)
        
    
    else:
        break
print(arr)
arr10 = np.array(arr)
print(arr10)

Want to enter list : y
Enter the elements : 1,2,3
Want to enter list : y
Enter the elements : 3,4,5
Want to enter list : y
Enter the elements : 6,7,8
Want to enter list : n
[(1, 2, 3), (3, 4, 5), (6, 7, 8)]
[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [6]:
 arr10.ndim

2

In [7]:
arr10.dtype

dtype('int32')

In [ ]:
#Type Casting

In [9]:
c = np.array([ [1,2.3], [3,4] ], dtype='<U32')
c.dtype

dtype('<U32')

In [10]:
print(c)

[['1' '2.3']
 ['3' '4']]


In [35]:
a=np.array((((2,3,4),(4,5,6)),((2,3,4),(4,5,6))), dtype='int', order = 'F')
print(a)

[[[2 3 4]
  [4 5 6]]

 [[2 3 4]
  [4 5 6]]]


In [36]:
a.ndim

3

In [49]:
a=0
[a+i for i in range(0,10)]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
a = np.arange(100).reshape(2,5,2,5)
print(a)
a.ndim

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[10 11 12 13 14]
   [15 16 17 18 19]]

  [[20 21 22 23 24]
   [25 26 27 28 29]]

  [[30 31 32 33 34]
   [35 36 37 38 39]]

  [[40 41 42 43 44]
   [45 46 47 48 49]]]


 [[[50 51 52 53 54]
   [55 56 57 58 59]]

  [[60 61 62 63 64]
   [65 66 67 68 69]]

  [[70 71 72 73 74]
   [75 76 77 78 79]]

  [[80 81 82 83 84]
   [85 86 87 88 89]]

  [[90 91 92 93 94]
   [95 96 97 98 99]]]]


4

In [66]:
ab = np.arange(3,9).reshape(2,3)
ab1 = np.arange(6,12).reshape(2,3)
print(ab)
print(ab1)

[[3 4 5]
 [6 7 8]]
[[ 6  7  8]
 [ 9 10 11]]


In [67]:
ab+ab1

array([[ 9, 11, 13],
       [15, 17, 19]])

In [68]:
ab-ab1

array([[-3, -3, -3],
       [-3, -3, -3]])

In [69]:
ab*ab1

array([[18, 28, 40],
       [54, 70, 88]])

In [70]:
ab/ab1

array([[0.5       , 0.57142857, 0.625     ],
       [0.66666667, 0.7       , 0.72727273]])

In [71]:
ab**2

array([[ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [123]:
arrr = np.array([[(1,3,2),(4,5,6),(14,15,16)],[(1,2,3,4),(11,12,13),(7,8,9,0)],[(2,3,1),(8,9,6),(1,1,1)]])
print(arrr)

[[(1, 3, 2) (4, 5, 6) (14, 15, 16)]
 [(1, 2, 3, 4) (11, 12, 13) (7, 8, 9, 0)]
 [(2, 3, 1) (8, 9, 6) (1, 1, 1)]]


In [124]:
#min value in row
arrr.min(1)

array([(1, 3, 2), (1, 2, 3, 4), (1, 1, 1)], dtype=object)

In [125]:
#min value in array
arrr.min()

(1, 1, 1)

In [126]:
#min value in column
arrr.min(0)

array([(1, 2, 3, 4), (4, 5, 6), (1, 1, 1)], dtype=object)

In [127]:
print(ab)
print(ab^2)

[[3 4 5]
 [6 7 8]]
[[ 1  6  7]
 [ 4  5 10]]


In [139]:
5^9      #5 - 0101, 9 - 1001 XOR(5,9) - 1100

12

In [141]:
arrr.max()

(14, 15, 16)

In [142]:
arrr.max(0)

array([(2, 3, 1), (11, 12, 13), (14, 15, 16)], dtype=object)

In [144]:
arrr.max(1)

array([(14, 15, 16), (11, 12, 13), (8, 9, 6)], dtype=object)

In [147]:
arrr.mean()

TypeError: unsupported operand type(s) for /: 'tuple' and 'int'

In [160]:
aq = np.array([[12,23,13,43,31],[51,20,44,53,54]])
print(aq)

[[12 23 13 43 31]
 [51 20 44 53 54]]


In [161]:
aq.mean()

34.4

In [162]:
aq.mean(0)

array([31.5, 21.5, 28.5, 48. , 42.5])

In [163]:
aq.mean(1)

array([24.4, 44.4])

In [164]:
np.median(aq,1)

array([23., 51.])

In [165]:
np.median(aq,0)

array([31.5, 21.5, 28.5, 48. , 42.5])

In [166]:
np.median(aq)

37.0

In [174]:
aa = np.array([[1,2,3],[4,5,6]])
print(aa)

[[1 2 3]
 [4 5 6]]


In [175]:
np.append(aa,[[1,1,1],[0,0,0]],1)

array([[1, 2, 3, 1, 1, 1],
       [4, 5, 6, 0, 0, 0]])

In [177]:
np.append(aa,[[9,9,9],[8,8,8]],0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 9, 9],
       [8, 8, 8]])

In [180]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [183]:
np.array([int(input("Enter value : ")) for i in range(10)]).reshape(2,5)

Enter value : 2
Enter value : 3
Enter value : 4
Enter value : 32
Enter value : 32
Enter value : 4
Enter value : 324
Enter value : 324
Enter value : 2
Enter value : 43


array([[  2,   3,   4,  32,  32],
       [  4, 324, 324,   2,  43]])

In [195]:
[i for i in range(10000000) if (i%10.5 == 0 and i%11.5==0 and i%12.5==0)]

[0,
 12075,
 24150,
 36225,
 48300,
 60375,
 72450,
 84525,
 96600,
 108675,
 120750,
 132825,
 144900,
 156975,
 169050,
 181125,
 193200,
 205275,
 217350,
 229425,
 241500,
 253575,
 265650,
 277725,
 289800,
 301875,
 313950,
 326025,
 338100,
 350175,
 362250,
 374325,
 386400,
 398475,
 410550,
 422625,
 434700,
 446775,
 458850,
 470925,
 483000,
 495075,
 507150,
 519225,
 531300,
 543375,
 555450,
 567525,
 579600,
 591675,
 603750,
 615825,
 627900,
 639975,
 652050,
 664125,
 676200,
 688275,
 700350,
 712425,
 724500,
 736575,
 748650,
 760725,
 772800,
 784875,
 796950,
 809025,
 821100,
 833175,
 845250,
 857325,
 869400,
 881475,
 893550,
 905625,
 917700,
 929775,
 941850,
 953925,
 966000,
 978075,
 990150,
 1002225,
 1014300,
 1026375,
 1038450,
 1050525,
 1062600,
 1074675,
 1086750,
 1098825,
 1110900,
 1122975,
 1135050,
 1147125,
 1159200,
 1171275,
 1183350,
 1195425,
 1207500,
 1219575,
 1231650,
 1243725,
 1255800,
 1267875,
 1279950,
 1292025,
 1304100,
 13161

In [200]:
ar99=[np.append(ar,i) for i in range(10)]
ar99

[array([6, 7, 8, 0, 6, 7, 8, 1, 6, 7, 8, 2, 6, 7, 8, 3, 6, 7, 8, 4, 6, 7,
        8, 5, 6, 7, 8, 6, 6, 7, 8, 7, 6, 7, 8, 8, 6, 7, 8, 9, 0, 6, 7, 8,
        0, 6, 7, 8, 1, 6, 7, 8, 2, 6, 7, 8, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6,
        7, 8, 6, 6, 7, 8, 7, 6, 7, 8, 8, 6, 7, 8, 9, 1, 6, 7, 8, 0, 6, 7,
        8, 1, 6, 7, 8, 2, 6, 7, 8, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 8, 6,
        6, 7, 8, 7, 6, 7, 8, 8, 6, 7, 8, 9, 2, 6, 7, 8, 0, 6, 7, 8, 1, 6,
        7, 8, 2, 6, 7, 8, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 8, 6, 6, 7, 8,
        7, 6, 7, 8, 8, 6, 7, 8, 9, 3, 6, 7, 8, 0, 6, 7, 8, 1, 6, 7, 8, 2,
        6, 7, 8, 3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 8, 6, 6, 7, 8, 7, 6, 7,
        8, 8, 6, 7, 8, 9, 4, 6, 7, 8, 0, 6, 7, 8, 1, 6, 7, 8, 2, 6, 7, 8,
        3, 6, 7, 8, 4, 6, 7, 8, 5, 6, 7, 8, 6, 6, 7, 8, 7, 6, 7, 8, 8, 6,
        7, 8, 9, 5, 6, 7, 8, 0, 6, 7, 8, 1, 6, 7, 8, 2, 6, 7, 8, 3, 6, 7,
        8, 4, 6, 7, 8, 5, 6, 7, 8, 6, 6, 7, 8, 7, 6, 7, 8, 8, 6, 7, 8, 9,
        6, 6, 7, 8, 0, 6, 7, 8, 1, 6, 